
version: "3.8"
services:
  frontend:
    deploy:
      replicas: 3
    build: ./frontend
    image: ${DOCKER_HUB_CREDS_USR}/todo-app-frontend:latest
    container_name: todo-app-frontend
    ports:
    - target: 5000
      published: 80
  backend:
    deploy:
      replicas: 3
    build: ./backend
    image: ${DOCKER_HUB_CREDS_USR}/todo-app-backend:latest
    container_name: todo-app-backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
    - target: 5000
      published: 5000
